#!/bin/bash

node src/main.js exampleslua2604/green --language LUA2604 --output exampleslua2604/green.lua
# node src/main.js examples2604/classes --language JS2604 --output examples2604/classes.js
# node src/main.js examples2604/machines --language JS2604 --output examples2604/machines.js
# node src/main.js testbed --language JS2604 --output testbed/testbed.js
#node src/main.js ../drakonhub2/dtsrc/drakon_canvas --language JS2604 --output drakon_canvas.js
