#!/bin/bash

node src/main.js exampleslua2604/green --language LUA2604 --output exampleslua2604/green.lua
node src/main.js exampleslua2604/classes --language LUA2604 --output exampleslua2604/classes.lua
# node src/main.js exampleslua2604/machines --language LUA2604 --output exampleslua2604/machines.lua
# node src/main.js testbed --language JS2604 --output testbed/testbed.js
#node src/main.js ../drakonhub2/dtsrc/drakon_canvas --language JS2604 --output drakon_canvas.js
